# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  time_zone: Europe/Amsterdam

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

recorder:
  db_url: "sqlite:///:memory:"
  purge_keep_days: 7
  include:
    domains:
      - light
      - sensor
      - automation
      - script

# Text to speech
tts:
  - platform: google_translate
    language: "nl"

input_boolean:
  wakeup_enabled:
    name: "Lichtwekker"
    initial: on
    icon: mdi:theme-light-dark
  wakeup_weekend:
    name: "Weekend"
    initial: on
    icon: mdi:calendar-blank
  auto_color_enabled:
    name: "Kleurverloop"
    initial: on
    icon: mdi:palette
  vacation:
    name: "Vakantie"
    icon: mdi:tent
  wake_up_in_progress:
    name: "Lichtwekker bezig"
    icon: mdi:weather-sunset-up

input_datetime:
  morning_start_time:
    name: "Ochtend"
    has_time: true
    has_date: false
  early_eve_start_time:
    name: "Avond"
    has_time: true
    has_date: false
    initial: "20:00"
  night_start_time:
    name: "Nacht"
    has_time: true
    has_date: false
    initial: "21:15"

input_number:
  wakeup_time_transition:
    name: "Min duur"
    icon: mdi:timer-sand-full
    initial: 15
    min: 5
    max: 60
    step: 5
  morning_start_hour:
    name: "Uur"
    icon: mdi:clock
    initial: 8
    min: 6
    max: 10
    step: 1
  morning_start_minutes:
    name: "Minuten"
    icon: mdi:clock-outline
    initial: 0
    min: 0
    max: 55
    step: 5

# Light groups
light:
  - platform: group
    name: all_lights
    entities:
      - light.woonkamer
      - light.nachtkastje
      - light.slaapkamer_plafond
      - light.gang
      - light.wc
      - light.badkamer

#lovelace: # uncomment to make UI editable in YAML files for custom cards
#  mode: yaml

python_script: # python scripts folder

telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret my_telegram_id
      - !secret gf_telegram_id
      - !secret home_group_telegram_id

notify:
  - name: teledobbyme
    platform: telegram
    chat_id: !secret my_telegram_id
  - name: teledobbygf
    platform: telegram
    chat_id: !secret gf_telegram_id
  - name: teledobbygroup
    platform: telegram
    chat_id: !secret home_group_telegram_id

# For Calendar integration
google:
  client_id: !secret GOOGLE_CLIENT_ID
  client_secret: !secret GOOGLE_CLIENT_SECRET

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
sensor: !include sensors.yaml
