- platform: template
  lights:
    ochtend_lamp:
      unique_id: '1762774307112'
      friendly_name: ochtend lamp
      value_template: "{{ states('switch.ochtend_lamp') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.ochtend_lamp
      turn_off:
        service: switch.turn_off
        entity_id: switch.ochtend_lamp