- alias: Wake-me up using bedroom lights
  id: '1565175229733'
  trigger:
  - platform: template
    value_template: >-
      {%- set transition_minutes = (states.input_number.wakeup_time_transition.state | int ) -%}
      {%- set t = states.sensor.time -%}
      {%- set in_x_minutes = now() + timedelta(minutes=transition_minutes) -%}
      {%- set alarm_end_str = states.input_datetime.morning_start_time.state -%}
      {{ in_x_minutes.strftime("%H:%M:00") == alarm_end_str }}
  condition:
  - condition: state
    entity_id: input_boolean.wakeup_enabled
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup_weekend
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - thu
      - fri
  action:
  - event: wake_up_lights_start_trigger
- alias: Change wake-up time based on sliders
  id: '1565175229702'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: input_number.morning_start_hour
  - platform: state
    entity_id: input_number.morning_start_minutes
  condition: []
  action:
  - service: input_datetime.set_datetime
    data_template:
      entity_id: input_datetime.morning_start_time
      time: >-
        {%- set h_in_s = (states('input_number.morning_start_hour') | int * 3600) -%}
        {%- set m_in_s = (states('input_number.morning_start_minutes') | int * 60) -%}
        {%- set total_seconds = h_in_s + m_in_s -%}
        {{ (total_seconds | timestamp_custom('%H:%M',False)) }}